flow/flow-for-vscode

- README.md
According to VS Code's [official documentation] (https://code.visualstudio.com/Docs/languages/javascript#_disable-syntax-validation-when-using-non-es6-constructs), the preference used for disabling syntax validation is now `javascript.validate.enable: false`. However, the documentation for this plugin states that the preference is `javascript.validate.syntaxValidation`. I might be mistaken, so please double-check.
> VS Code 1.1 uses a different preference for disabling syntax validation

- lib/utils/util.js
'which' is not available on windows unless git tools have been installed to the users path.
i took this behavior:
https://github.com/flowtype/flow-for-vscode/blob/2ee543c/lib/pkg/flow-base/lib/FlowHelpers.js#L139
and added it to the missing places.
> use where command to locate flow on windows

- lib/flowDiagnostics.js
Hello there, looks like if Flow gives an error with 0 as the line, this extension will not show results:
> `flow status --pretty packages/jest-editor-support/src/test_reconciler.js | pbcopy`
```json
{
"flowVersion":"0.36.0",
"errors":[
{
"kind":"internal",
"level":"error",
"message":[
{
"context":null,
"descr":"Internal error: Failure(\"attempt to refine type TestReconcilationState\")\n",
"type":"Blame",
"loc":{
"source":"/Users/orta/dev/projects/vscode/jest/packages/jest-editor-support/src/test_reconciler.js",
"type":"SourceFile",
"start":{"line":0,"column":1,"offset":0},
"end":{"line":0,"column":0,"offset":0}
},
"path":"/Users/orta/dev/projects/vscode/jest/packages/jest-editor-support/src/test_reconciler.js",
"line":0,
"endline":0,
"start":1,
"end":0
}
]
},
{
...
```
This fixes that 👍
> Ensure that we do not pass a negative number to VS Code for error diagnostics

- lib/flowLogging.js
- lib/flowMain.js
- lib/pkg/nuclide-logging/lib/consoleAppender.js
Bah, looks like the a change online endings for flowMain as with #53  - so far this seems to be the only file that has this issue, is it worth having it switched over (like these diffs are doing?)
This PR adds the ability for users to see any problems, perviously to debug a "why isn't this working?" you would have to open the web inspector for VS Code.
---
I initially tried building this via log4js' appender system, but I couldn't get it to ever echo anything out. 
I'm not 100% on whether it's a good idea to add VS Code specific bits inside any `lib/pkg/nuclide-*` but it looks like the libraries are pretty mature on nuclide's sides, and so it feels like an ok idea.
> Add support for showing Flow messages to the User via an output channel

- lib/flowMain.js
- lib/pkg/flow-base/lib/FlowHelpers.js
- lib/pkg/flow-base/lib/FlowProcess.js
- lib/utils/util.js
- package.json
Addresses https://github.com/flowtype/flow-for-vscode/issues/41 by proxy too.
We have multiple apps that use different versions of Flow, which makes it tough to keep VS Code in a good state. We couldn't use an absolute path, or per-project settings (as they wouldn't work per user) and so I think this is a good fallback.
> Support automatically checking for the node_modules version of Flow

- compile.sh
- package.json
The package.json scripts delegated to a `.sh` script, which does not work on Windows. The easiest thing to do is to just have the `package.json` run babel directly.
To test, I checked out this branch on Windows and OSX. I opened the repo with vscode, and hit CMD+Shift+B (CTR+Shift+B on Windows). Previously this failed to build on Windows. Now it builds fine on both.
Also made sure that `vsce package` works on both Windows and OSX (though had to make sure to upgrade vsce to >= 1.16 due to https://github.com/Microsoft/vscode-vsce/issues/130)
If this command gets more complicated, we probably could switch to a more cross-platform scripting language, like JavaScript 😛
> Fix the compile step to work on Windows as well

- .vscode/launch.json
- .vscode/tasks.json
- CHANGELOG.md
You can set a pre-launch task to ensure that running the extension in dev mode enforces the watcher to start.
Also adds a CHANGELOG, I've got no qualms about what the format should be, so I just wrote one similar to how I do it for [Danger](https://github.com/danger/danger-js/blob/master/changelog.md).
Fixes #59
> Hitting run when debugging starts the babel watcher 

- README.md
I was unable to find clear instructions on how to setup VS Code to debug Flow code so thought it'd be worth documenting my setup. This works with both the "node" and "node2" debugger protocols.
I've found flow-remove-types to work most robustly. With Babel, VS Code will always pause on the first line.
The babel setup is partially taken from https://medium.com/@katopz/how-to-debug-es6-nodejs-with-vscode-8d00bd6c4f94, though the sourceMaps configuration documented there is not required when using `"retainLines": true`. I've not been able to get sourceMaps to work with Babel and VS Code, see Microsoft/vscode#5728 for more on the current status.
> Document debugger setup for flow-remove-types and Babel.

- CHANGELOG.md
- lib/pkg/flow-base/lib/FlowHelpers.js
- lib/utils/util.js
- package.json
#69 
By using the absolute path to the where executable provided by Windows
we avoid issues with other variants of the where command on the user's
path.
C:\Windows\System32\where.exe can be used to search a directory:
where /r <dir> <command>
> Always use where command provided by Windows

- .vscode/tasks.json
- README.md
- lib/flowDiagnostics.js
- lib/flowLogging.js
- lib/flowStatus.js
- lib/utils/util.js
- package.json
Implements status indicator as per #40
> Status indicator

- .vscode/tasks.json
- README.md
- lib/flowDiagnostics.js
- lib/flowStatus.js
- lib/utils/util.js
- package.json
Please note that this pull unfortunately includes changes from #85, I'll rebase this once hopefully #85 lands. This change implements short term solution described in #26. To be clear if you have edits in multiple files that aren't saved, it will report errors for the active document as if it was saved but will ignore all other unsaved changes because:
1. Trying to type check as if all unsaved changes were saved isn't necessarily a desired or expected behavior. I personally like to make edits to files until it type checks and only then move on to other file. When I get blocked, I tend to move on to other file, with a plan to return to the blocker. With such work flow type checking all unsaved changes isn't a desired option.
2. From what I understand currently it's not possible to do that …
> Check on edit

- .vscode/tasks.json
- README.md
- lib/flowDiagnostics.js
- lib/flowMain.js
- lib/flowStatus.js
- lib/pkg/flow-base/lib/FlowRootContainer.js
- lib/utils/util.js
- package.json
- Add `playground/.flowconfig` blank file to workaround flow’s requirement to have `.flowconfig` file (see facebook/flow#389)
- Add `playground/try.js` blank file that will be used as file parameter when running `flow check-contents` so that `playground` will be treated as project root & defaults will be used for flow configuration.
- Made changes to flowDiagnostics module so that untitled js documents with `@flow` pragma are type checked with flow similar to how flowptype.org/try does it.
P.S.: This pull is based off #87 so relevant changes are starting from  c5aa338
> Implement flow support for unsaved docs as per #84

- .flowconfig
- lib/flowHover.js
- package.json
Huge fan of this library! Been using it a lot when working with Flow at my current job.
When working with complex types that are deeply nested, it's hard to read through the whole type tooltip because there is no indentation.
This PR is based off the Flow type tooltips from this other plugin: https://github.com/gcazaciuc/vscode-flow-ide. This seems to be no longer actively worked on, with functionality being ported over to this library.
> use js-beautify for Flow Type hovers

- lib/flowDiagnostics.js
**Summary**
There's some redundancy in messages displayed by flow extension. This PR attempts to remove extra `[flow]` annotation which is unnecessary, as it's already present in message.
Before:
After:
> Remove redundant [flow] annotation

- lib/flowCoverage.js
- lib/flowDiagnostics.js
**Summary**
Flow coverage support. 
StatusBar (clicking toggles uncovered code mode):
Uncovered code mode:
> Add flow coverage support

- README.md
This updates the README to note about the JavaScript Atom Grammar which @siegebell noted in https://github.com/flowtype/flow-for-vscode/issues/103#issuecomment-295431698 👍
> Add a note about the atom JS grammar

- CHANGELOG.md
- lib/pkg/flow-base/lib/FlowHelpers.js
- package.json
> Add bundled flow

- lib/flowStatus.js
When having multiple plugins that use spinners, it's impossible to tell if the user sees a Flow plugin spinner or not.
Fixes #133
> Make Flow spinner distinctive

- lib/flowDiagnostics.js
- lib/utils/util.js
- package.json
This PR allows the user to set the file extensions to consider for flow processing.  This resolves PR #145.
Currently `flow-for-vscode` is [hardcoded](https://github.com/flowtype/flow-for-vscode/blob/master/lib/flowDiagnostics.js#L134-L136) to only consider `.js, .jsx` file extensions.
NOTE: The solution in this PR is not ideal and should reach into the `.flowconfig` relevant for the file being considered for checking - but it looked like that would take a reasonable amount of refactoring of the code flow.
> Add flow.fileExtensions configuration setting for file extensions

- lib/flowDiagnostics.js
This PR fixes #157 (I haven't checked all the issues).
Currently `activeTextEditor` is being [cached](https://github.com/flowtype/flow-for-vscode/blob/master/lib/flowDiagnostics.js#L28) which invalidates checks against `activeTextEditor` within event [handlers](https://github.com/flowtype/flow-for-vscode/blob/master/lib/flowDiagnostics.js#L46-L64).
> bugfix: don't cache activeTextEditor used in workspace event handlers

- lib/pkg/flow-base/lib/FlowHelpers.js
`flow.useNPMPackagedFlow` wasn't adequate for my use-cases (node_modules not at root, a copy for flow-bin outside of node-modules, etc). 
I was resorting to this hack: `"postinstall": "cp .vscode/settings.example.json .vscode/settings.json && sed -i '' \"s ROOT_REPLACE_ME $(pwd) \" .vscode/settings.json"`
Ideally this would be solved by vscode; there is an open issue: https://github.com/Microsoft/vscode/issues/2809 however it seems harmless to add this. 
I tested locally with:
- setting defined correctly (`"flow.pathToFlow": "${workspaceRoot}/my-flow"`)
- setting defined incorrectly (`"flow.pathToFlow": "${workspaceRoot}/my-nonexistent-flow"`)
- setting undefined (checking that `.config('pathToFlow').replace` does not throw)
> Allow workspaceRoot variable in pathToFlow

- lib/flowLSP.js
- lib/flowMain.js
This PR simply updates the `DocumentSelector` (used for registering language services) to specify a `file` scheme for both the `javascript` and `javascriptreact` languages. 
In preparation for [Visual Studio Live Share](https://aka.ms/vsls) adding support for "guests" to receive remote language services for Flow, this PR helps ensure that "guests" within a Live Share session will have their language services be entirely derived from the remote/host side, which provides a more accurate and project-wide experience. "Guests" in Live Share see documents using the `vsls` scheme, and so by limiting to just `file`, this allows the Live Share "proxy language server" to capture language service requests and send them to the local Flow language server on the host's machine (which would see `file` …
> [Discussion] [Live Share] Restrict javascriptreact documents to file scheme

- lib/flowDiagnostics.js
This is a follow-up to #230, since I forgot to limit diagnostics to local files as well.
// CC @orta
> [Live Share] Limit linting to localfiles

- README.md
* Move the _Getting started_ link to the top and fix the link URLs to point to the new website directly.
* Improve(?) the Setup section
* change wording
* make sure the GIF is discoverable (see #235)
* bring back the `javascript.validate.enable` info as an alternative (see #235)
* Add link to marketplace in Installation section.
> Improve configuration in README

- lib/flowLSP.js
The Flow LS doesn't know how to process url-encoded Windows file paths, making the extension not work on that OS unless it is disabled.
This fixes #238
> Disable URL-encoding of paths in the language client to make LSP work on Windows

- README.md
Looks like I've forgotten to put it in the readme.
> Document `useLSP` config option

- package.json
- yarn.lock
Just updating the deps to get it working.
This PR is currently blocked by https://github.com/flowtype/flow-language-server/pull/82. After this is released, we can update the `flow-language-server` dep once again and get this feature in.
Fixes #254
Here's a preview of richer diagnostics (note the links):
> LSP: make use of `relatedInformation` for richer diagnostics

- README.md
- lib/flowCoverage.js
- lib/utils/util.js
- package.json
I find the uncovered code feature to be really helpful. Unfortunately, it is not activated by default and I need to click on the status bar item every time.
I am adding this option to enable it by default while keeping the status bar item toggle working.
> Add `showUncovered` config option to activate uncovered code report by default

- README.md
Github link does not understand capitals.
> fix typo broken link in readme

- lib/flowLSP.js
- lib/index.js
- lib/pkg/flow-base/lib/FlowHelpers.js
Currently, when `useLSP` is true, the extension ignores the `Path To Flow` and `Use NPMPackaged Flow` settings and attempts to download the appropriate flow binary for the project. This PR switches flow-language-server to always take a path to the flow binary, using the same resolution process as when `useLSP` is false. 
Tested on Mac and Windows with global Flow, npm-packaged flow, and extension-bundled Flow.
* Disabled the auto-downloading function of flow-language-server. Since it's not exposed to the extension users, it feels hard to reason about. See #273, https://github.com/flowtype/flow-language-server/issues/79
* Switched `--debug` to `--inspect` when debugging the extension in LSP mode -- this was causing a crash when using the current LTS version of node.
* flow-language-server …
> Use same path to Flow when useLSP is true

- README.md
Deprecated here https://code.visualstudio.com/docs/editor/variables-reference#_why-isnt-workspaceroot-documented
> Update deprecated `workspaceRoot` variable

- package.json
> fix: activate plugin only for js projects

- flow-typed/npm/semver_v5.6.x.js
- lib/flowLSP/FlowLanguageClient/createMiddleware.js
- lib/flowLSP/utils/assertFlowSupportsLSP.js
fix https://github.com/facebook/flow/issues/7835
> fix(lsp): accept flow release candidate version

- yarn.lock
https://nvd.nist.gov/vuln/detail/CVE-2019-10746
> mixin-deep is vulnerable to Prototype Pollution in versions before 1.3.2 and version 2.0.0. The function mixin-deep could be tricked into adding or modifying properties of Object.prototype using a constructor payload.
Test plan:
```
yarn build && yarn test
```
> Update mixin-deep dependency due to security vulnerability

- README.md
- package.json
Having this setting default to `true` is a security risk, so this changes the default to `false` (with additional info in the README about where and why one might use it) until we can build a better solution.
> flow.useNPMPackagedFlow defaults to false

- lib/flowLSP/FlowLanguageClient/createMiddleware.js
- lib/flowLSP/utils/formatFlowMarkDownString.js
`flow-for-vscode` re-formats type descriptions as JavaScript markdown blocks which results in links not being clickable. We should use the default markdown formatter for non-flowtype code blocks.
Allows package maintainers to provide a better developer experience by adding contextual links.
1. Add a comment to a type:
```js
const DefaultAvatar = ({
accessibilityLabel,
}: {|
/** Label for screen readers https://test.com/ */
accessibilityLabel?: string,
|}) => {
```
2. Hover over the type
3. Ensure the link inside the hover is clickable
> feat(vscode): allow clickable links on hover for type descriptions
